### ISSUE TITLE
quitting

### ISSUE THREAD

**Issue by aoloe** [replit/play#3]
nice project!

i had one issue: quitting.

i could not find a default keybinding for quitting (ctrl-q?) nor how to trigger a quit action...

**Comment by Glench** [comment]
You can now press ctrl+q or command+q (or click the window's "close"/"x" button) to quit out. Thanks for the comment!

How did you find this library anyway?

**Comment by aoloe** [comment]
thanks!

how i heard about it? through the hn thread on repl.it GFX...

how i like it? my first impression is good...
i'm a bit "scared" about the heavy use of decorators and of async/await...
but i wonder if this matters for kids.
(having two functions with the exact same name (and same decorator ) like in the [last sample in the README](https://github.com/replit/play#whats-with-all-this-asyncawait-stuff-is-this-python) bothers me a bit: it clashes with the idea that every function needs a unique name... it matches what they have experienced in scratch, but it might be hard to explain how it works to a kid... and how explain them why they need distinct names for their other functions? ...) 

one remark: i guess that you know about pygame-zero, which has a similar goal as your project. it would be nice to see a statement about the difference you see between the two libraries. or, in a more "neutral" way, what are the characteristics of python-play?

anyway, it's amazing to see what you have achieved in "so little time"!

**Comment by Glench** [comment]
Cool thanks for the feedback. I just made it so you don't need to use async functions if there's not awaitables in the function. See the updated README for examples.

Because Python doesn't have anonymous code blocks, we unfortunately had to use named functions. When trying to come up with a name for a function that's only mentioned once, we just wanted something as short as possible, like `do()`.

Python Play was also designed to be used in the context of a custom Repl.it IDE that's coming soon. This IDE will need to automatically paste in code blocks, so by default those blocks will probably be named `do()`.

As for Python Play's characteristics — it was designed to be used by new programmers in the same way MIT's Scratch is. As such, it was created to make it as likely as possible that a brand new programmer would have a compelling experience coding in their first few minutes.
